### ISSUE TITLE
Only Download Index.html file

### ISSUE THREAD

**Issue by EbuXa** [jsvine/waybackpack#40]
Hi jsvine,
when i want to download the spesific snapshot of whole pages of my site it only download the index.html file and the folder of the snapshot, the command is: waybackpack example.com -d downfolder/ --follow-redirects --from-date 201901

**Comment by lioriluz** [comment]
same for me. Downloads the index.html 
waybackpack domain.com -d ~/Downloads/domain-wayback --from-date 20190317190833  --to-date 20190317190833 --follow-redirects

**Comment by jsvine** [comment]
Thanks for your interest in this project! Currently, `waybackpack` only supports downloading individual URLs, rather than entire sites. It does seem, however, to be a worthwhile feature to add in the future. There is additional discussion here: https://github.com/jsvine/waybackpack/issues/8

Given that there is more discussion on that thread, I am closing this one.
