### ISSUE TITLE
Save all HTML files in one place

### ISSUE THREAD

**Issue by Mennaruuk** [jsvine/waybackpack#54]
Hello jsvine, hope your health is okay.

I noticed that waybackpack saves HTML files in nested folders. I think it's pretty neat, and it has its set of advantages (esp. with organization). However, it can also be cumbersome and add another step to viewing these HTML files.

Is there a way to save all HTML files in an event in the same folder where waybackpack was ran?

Thank you very much.

**Comment by jsvine** [comment]
Hi @Mennaruuk. Currently there is not a way to do this *directly* in waybackpack, in large part because this would result in different pages from the same domain (e.g., /about/index.html and /bio/index.html) overwriting one another. But I believe you could achieve your goal through other means, such as the approach suggested in this Stack Overflow answer: https://superuser.com/a/419113
